networks:
  backend:

volumes:
  sql1_data:
  sql2_data:
  sql3_data:
  sql4_data:
  sql5_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

x-common-variables: &common-variables
  TZ: America/Sao_Paulo
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false

services:
  sql1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql1
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "14333:1433"
    volumes:
      - sql1_data:/var/opt/mssql
    networks:
      - backend
      
  sql2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql2
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "14334:1433"
    volumes:
      - sql2_data:/var/opt/mssql
    networks:
      - backend
      
  sql3:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql3
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "14335:1433"
    volumes:
      - sql3_data:/var/opt/mssql
    networks:
      - backend
      
  sql4:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql4
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "14336:1433"
    volumes:
      - sql4_data:/var/opt/mssql
    networks:
      - backend
      
  sql5:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql5
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
      MSSQL_PID: "Developer"
    ports:
      - "14337:1433"
    volumes:
      - sql5_data:/var/opt/mssql
    networks:
      - backend      
      
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
      
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: apigateway
    depends_on:
      catalogservice:
        condition: service_started
      orderservice:
        condition: service_started
      sql3:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      <<: *common-variables
    ports:
      - "5000:8080"
      - "5001:8081"
    networks:
      - backend
      
  webservices:
    build:
      context: .
      dockerfile: Web/Dockerfile
    container_name: webservices
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      <<: *common-variables
    ports:
      - "5002:8080"
      - "5003:8081"
    networks:
      - backend
      
  catalogservice:
    build:
      context: .
      dockerfile: CatalogService/Dockerfile
    container_name: catalogservice
    depends_on:
      sql2:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      <<: *common-variables
    networks:
      - backend
      
  oauthservices:
    build:
      context: .
      dockerfile: OAuthServices/Dockerfile
    container_name: oauthservices
    depends_on:
      sql4:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      <<: *common-variables
    ports:
      - "5004:8080"
      - "5005:8081"
    networks:
      - backend
      
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    container_name: orderservice
    depends_on:
      sql2:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__User: "guest"
      RabbitMQ__Password: "guest"
      <<: *common-variables
    networks:
      - backend
      
  workercatalog:
    build:
      context: .
      dockerfile: WorkerCatalog/Dockerfile
    container_name: workercatalog
    depends_on:
      sql2:
        condition: service_started
      sql5:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__User: "guest"
      RabbitMQ__Password: "guest"
      <<: *common-variables
    networks:
      - backend
      
  workerordem:
    build:
      context: .
      dockerfile: WorkerOrdem/Dockerfile
    container_name: workerordem
    depends_on:
      sql2:
        condition: service_started
      sql5:
        condition: service_started
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Port: "5672"
      RabbitMQ__User: "guest"
      RabbitMQ__Password: "guest"
      <<: *common-variables
    networks:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    networks:
      - backend
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - backend
